module.exports = {
  WORKER_EVENT_EXIT: 'WORKER_EVENT_EXIT',
  WORKER_EVENT_MESSAGE: 'WORKER_EVENT_MESSAGE',
  WORKER_EVENT_ERROR: 'WORKER_EVENT_ERROR',
  WORKER_EVENT_UNHANDLED_ERROR: 'WORKER_EVENT_UNHANDLED_ERROR',

  WORKER_TYPE_BUCKET: 'WORKER_TYPE_BUCKET',
  WORKER_TYPE_SOCKET: 'WORKER_TYPE_SOCKET',
  WORKER_TYPE_API: 'WORKER_TYPE_API',

  WORKER_WAIT_TIMEOUT: 500
};
